baseURL = 'https://youthvoyager.github.io/'
languageCode = 'zh-cn'
title = '少年游的技术博客'
theme = 'PaperMod'

[params]
  ShowToc = true  # 默认显示目录

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Rust"
    url = "/categories/rust/"
    weight = 30

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 40
  
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 50
